# Generated by Django 2.0.2 on 2018-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtooncrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
