# Generated by Django 2.0.2 on 2018-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtooncrawler', '0002_auto_20180204_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='created_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
